import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import request from 'supertest';
process.env.DATA_DIR = path.resolve('test-results', `onboarding-${randomUUID()}`);
process.env.ADMIN_PASSWORD = 'Onboarding-Test-Password-Only';
const { createApp } = await import('../server/app.ts');
const { PrinterService } = await import('../server/printers.ts');
const { db, settings, onboarding } = await import('../server/db.ts');
let available = true;
const service = () => new PrinterService(async () => ({ backend: 'windows', printers: [{ name: 'Test PDF', driver: 'Test', connection: '虚拟', virtual: true, available, status: 'test', systemDefault: false }] }), 'test-host');
const app = createApp(service()), admin = request.agent(app), guest = request.agent(app);
after(() => db.close());
test('first-run setup is authenticated, persisted per step, validated and gates checkout until completion', async () => {
  await guest.get('/api/admin/onboarding').expect(401);
  await guest.put('/api/admin/onboarding').send({ action: 'complete', accepting: true }).expect(401);
  await admin.post('/api/admin/login').send({ password: process.env.ADMIN_PASSWORD }).expect(200);
  assert.equal((await admin.get('/api/admin/session')).body.setupRequired, true);
  assert.equal((await admin.get('/api/admin/onboarding')).body.step, 0);
  await admin.put('/api/admin/onboarding').send({ action: 'complete', accepting: true }).expect(409);
  await admin.put('/api/admin/onboarding').send({ action: 'identity', shopName: '  ', deviceName: 'A', address: '' }).expect(400);
  await admin.put('/api/admin/onboarding').send({ action: 'identity', shopName: '新店', deviceName: '东门一号', address: '校门口' }).expect(200);
  const restartedApp = createApp(service()), resumed = request.agent(restartedApp);
  await resumed.post('/api/admin/login').send({ password: process.env.ADMIN_PASSWORD }).expect(200);
  const progress = (await resumed.get('/api/admin/onboarding')).body;
  assert.equal(progress.step, 1); assert.equal(progress.settings.shopName, '新店');
  await resumed.put('/api/admin/onboarding').send({ action: 'printer' }).expect(409);
  await resumed.put('/api/admin/printers/default').send({ name: 'Test PDF' }).expect(200);
  assert.equal((await resumed.put('/api/admin/onboarding').send({ action: 'printer' }).expect(200)).body.step, 2);
  assert.equal((await guest.get('/api/device')).body.accepting, false);
  await guest.post('/api/files').attach('file', 'examples/sample-photo.png').expect(409);
  await guest.post('/api/quotes').send({}).expect(409);
  await resumed.put('/api/admin/onboarding').send({ action: 'complete', accepting: true }).expect(409);
  for (const price of [0, -1, 1.2, 10001]) await resumed.put('/api/admin/onboarding').send({ action: 'pricing', simplexPrice: price, duplexPrice: 15 }).expect(400);
  await resumed.put('/api/admin/onboarding').send({ action: 'pricing', simplexPrice: 30, duplexPrice: 15 }).expect(200);
  assert.equal((await resumed.get('/api/admin/onboarding')).body.step, 3);
  available = false;
  await resumed.put('/api/admin/onboarding').send({ action: 'complete', accepting: true }).expect(409);
  assert.equal(onboarding().completed, false);
  available = true;
  const complete = await resumed.put('/api/admin/onboarding').send({ action: 'complete', accepting: false }).expect(200);
  assert.equal(complete.body.completed, true); assert.equal(settings().accepting, false);
  assert.equal(settings().simplexPrice, 30); assert.equal(settings().duplexPrice, 15);
  assert.equal((await resumed.get('/api/admin/session')).body.setupRequired, false);
  // Duplicate completion must not overwrite later merchant choices.
  await resumed.put('/api/admin/onboarding').send({ action: 'complete', accepting: true }).expect(200);
  assert.equal(settings().accepting, false);
  await resumed.put('/api/admin/settings').send({ ...settings(), accepting: true }).expect(200);
  assert.equal((await request(createApp(service())).get('/api/device')).body.accepting, true);
  await resumed.delete('/api/admin/printers/default').expect(200);
  assert.equal((await resumed.get('/api/admin/session')).body.setupRequired, false);
  assert.equal((await resumed.get('/api/device')).body.accepting, false);
});
